### ISSUE TITLE
ESM package is missing

### ISSUE THREAD

**Issue by Spreizu** [nuxt-community/nuxt-generate-cluster#34]
Please add esm package as a devDependency, otherwise nuxt-generate-cluster is not working with Nuxt 2.15.2.

**Comment by TakCastel** [comment]
```
    "nuxt": "^2.15.8",
    "nuxt-generate-cluster": "^2.7.0",
```

```bash
~/project $ yarn generate

yarn run v1.22.11
$ nuxt-generate
node:internal/modules/cjs/loader:927
  throw err;
  ^

Error: Cannot find module 'esm'
Require stack:
- /project/node_modules/nuxt-generate-cluster/bin/nuxt-generate.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/project/node_modules/nuxt-generate-cluster/bin/nuxt-generate.js:83:17)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/project/node_modules/nuxt-generate-cluster/bin/nuxt-generate.js'
  ]
}
```

Installed esm in package.json as devDependency and now it works.

Can you please include it in dep ? Thank you for your work 🙏
